export default {
    CREATE_COUNT: "CREATE_COUNT",
    UPDATE_COUNT: "UPDATE_COUNT",
    DELETE_COUNT: "DELETE_COUNT",
    LOAD_COUNT: "LOAD_COUNT",
    MORE_COUNT: "MORE_COUNT",
    LESS_COUNT: "LESS_COUNT"

}