export default {
    CREATE_PRODUCT_SHOPPING: "CREATE_PRODUCT_SHOPPING",
    UPDATE_PRODUCT_SHOPPING: "UPDATE_PRODUCT_SHOPPING",
    DELETE_PRODUCT_SHOPPING: "DELETE_PRODUCT_SHOPPING",
    LOAD_PRODUCT_SHOPPING: "LOAD_PRODUCT_SHOPPING"

}