export default {
  CREATE_TOTAL_SUM_PRODUCTS__API: "CREATE_TOTAL_SUM_PRODUCTS__API",
  UPDATE_TOTAL_SUM_PRODUCTS__API: "UPDATE_TOTAL_SUM_PRODUCTS__API",
  DELETE_TOTAL_SUM_PRODUCTS__API: "DELETE_TOTAL_SUM_PRODUCTS__API",
  LOAD_TOTAL_SUM_PRODUCTS__API: "LOAD_TOTAL_SUM_PRODUCTS__API",
  MORE_COUNT: "MORE_COUNT",
  LESS_COUNT: "LESS_COUNT",
};
