export default {
  CREATE_PRODUCT__API: "CREATE_PRODUCT__API",
  UPDATE_PRODUCT__API: "UPDATE_PRODUCT__API",
  DELETE_PRODUCT__API: "DELETE_PRODUCT__API",
  LOAD_PRODUCT__API: "LOAD_PRODUCT__API",
};
