export default {
  CREATE_PURCHASE__API: "CREATE_PURCHASE__API",
  UPDATE_PURCHASE__API: "UPDATE_PURCHASE__API",
  DELETE_PURCHASE__API: "DELETE_PURCHASE__API",
  LOAD_PURCHASE__API: "LOAD_PURCHASE__API",
};
